version: '3.8'
services:
  app:
    build: "./app"
    container_name: python311
    ports:
     - "8080:8080"
    tty: true
    stdin_open: true
    working_dir: /workspace/eim
    volumes:
      - type: bind
        source: ..
        target: /workspace/eim
    depends_on:
      - dynamodb-admin
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYIDEXAMPLE'
      REGION: 'eu-west-1'
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    tty: true
    container_name: dynamodb-admin
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb-local
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000